apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: ""
      version: v1
      kind: Service
      name: frontend
      namespace: guestbook
    patch: |
      - op: replace
        path: /spec/selector
        value:
          app: wrong-label     
